name: Deploy sitemap to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload sitemap folder to artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./  # Root directory where your sitemap.xml is

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
